export const GET_DATA_FETCHING = "GET_DATA_FETCHING"
export const GET_DATA_SUCCESS = "GET_DATA_SUCCESS"
export const GET_DATA_FAIL = "GET_DATA_FAIL"

export const CREATE_DATA = "CREATE_DATA"
export const CREATE_DATA_SUCCESS = "CREATE_DATA_SUCCESS"
export const CREATE_DATA_FAIL = "CREATE_DATA_FAIL"

export const UPDATE_DATA = "UPDATE_DATA"
export const UPDATE_DATA_SUCCESS = "UPDATE_DATA_SUCCESS"
export const UPDATE_DATA_FAIL = "UPDATE_DATA_SUCCESS"

export const REMOVE_DATA = "REMOVE_DATA"
export const REMOVE_DATA_SUCCESS = "REMOVE_DATA_SUCCESS"
export const REMOVE_DATA_FAIL = "REMOVE_DATA_FAIL"

export const LOGIN = "REQUEST"
export const LOGIN_FAIL = "LOGIN_FAIL"
export const LOGOUT = "LOGOUT"

export const REGISTER = "REGISTER"
export const REGISTER_FAIL = "REGISTER_FAIL"


export const SHORTPOST_CREATE_DATA = "SHORTPOST_CREATE_DATA"
export const SHORTPOST_CREATE_DATA_FAIL = "SHORTPOST_CREATE_DATA_FAIL"

export const SHORTPOST_GET_DATA = "SHORTPOST_GET_DATA"
export const SHORTPOST_GET_DATA_SUCCESS = "SHORTPOST_GET_DATA_SUCCESS"
export const SHORTPOST_GET_DATA_FAIL = "SHORTPOST_GET_DATA_FAIL"

export const SHORTPOST_REMOVE_DATA = "SHORTPOST_REMOVE_DATA"
export const SHORTPOST_REMOVE_DATA_FAIL = "SHORTPOST_REMOVE_DATA_FAIL"

export const SHORTPOST_UPDATE_DATA = "SHORTPOST_UPDATE_DATA"
export const SHORTPOST_UPDATE_DATA_FAIL = "SHORTPOST_UPDATE_DATA_FAIL"

export const LIKE_UPDATE_DATA = "LIKE_UPDATE_DATA"
export const LIKE_UPDATE_DATA_FAIL = "LIKE_UPDATE_DATA_FAIL"


export const CHANGE_SETTINGS = "CHANGE_SETTINGS"
export const CHANGE_SETTINGS_FAIL = "CHANGE_SETTINGS_FAIL"

export const GET_USER = "GET_USER"
export const GET_USER_FAIL = "GET_USER_FAIL"

export const UPDATE_CREATER_NAME = "UPDATE_CREATER_NAME"
export const UPDATE_CREATER_NAME_FAIL = "UPDATE_CREATER_NAME_FAIL"

export const USERDETAILS = "USERDETAILS"
export const USERDETAILS_FAIL = "USERDETAILS_FAIL"

export const LIKE_USER = "LIKE_USER"
export const LIKE_USER_FAIL = "LIKE_USER_FAIL"

export const DELETE_ACCOUNT = "DELETE_ACCOUNT"
export const DELETE_ACCOUNT_FAIL = "DELETE_ACCOUNT_FAIL"

export const CHECK_ACCOUNT = "CHECK_ACCOUNT"
export const CHECK_ACCOUNT_FAIL = "CHECK_ACCOUNT_FAIL"

export const CHANGE_PASSWORD = "CHANGE_PASSWORD"
export const CHANGE_PASSWORD_FAIL = "CHANGE_PASSWORD_FAIL"